#!/bin/bash

# ------------------------------------------------------------------
#  Author: Matthew Remmel (matt.remmel@gmail.com) 
#  Title: IP
#
#  Description: IP is a command line util to display the primary
#               internal IP address, as well as the external IP
#               address. The script uses 'wget' and 'ipecho.net'
#               to retrieve the external IP address. The output
#               is formatted and echoed to standard out.
#
#  Return:      A 1 is returned if the external IP address cannot 
#               be retreived. A 0 is returned otherwise. 
# ------------------------------------------------------------------

# --- Version and Usage ---
VERSION=0.1.0
USAGE="Usage: ip"


# --- Main Body ---
exitcode=0

# Check that dependencies are installed
command -v wget >/dev/null 2>&1 || { echo >&2 "[ERROR] Dependency wget not installed. Exiting."; exit 1; }

# Get internal IP address
localip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'`

# Get external IP address if available
ipecho=`wget -qO- http://www.ipecho.net/plain`

if [ $? -eq 0 ]; then
    externalip=$ipecho
else
    externalip="Could not retreive external IP address. Check connection."
    exitcode=1
fi

# Print IP address information
echo "Internal: $localip"
echo "External: $externalip"

exit $exitcode